let CustomErrorHandler,JwtService;_6a5‍.x([["default",()=>_6a5‍.o]]);_6a5‍.w("../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_6a5‍.w("../services/JwtService",[["default",["JwtService"],function(v){JwtService=v}]]);


const auth = async (req, res, next) => {
  let authHeader = req.headers.authorization
  if (!authHeader) {
    return next(CustomErrorHandler.unAuthorized('No Token in here'))
  }
  const token = authHeader.split(' ')[1]

  try {
    const { _id, name, email, role } = JwtService.verify(token)

    const user = {
      _id,
      name,
      email,
      role
    }
    req.user = user
    next()
  } catch (error) {
    return next(CustomErrorHandler.unAuthorized('something Went Wrong'))
  }
}

_6a5‍.d(auth);
